### ISSUE TITLE
JavaScript Error on Discord Startup

### ISSUE THREAD

**Issue by v-ersacee** [denBot/BetterDiscordOSXInstaller#9]
Uncaught exception:
 TypeError: Cannot read property 'forEach' of undefined
    at keys.forEach.key (/Users/vasilios/Library/Application Support/discord/0.0.250/modules/discord_desktop_core/core/app/node_modules/betterdiscord/lib/BetterDiscord.js:797:23)
    at Array.forEach (native)
    at parseEmoteData (/Users/vasilios/Library/Application Support/discord/0.0.250/modules/discord_desktop_core/core/app/node_modules/betterdiscord/lib/BetterDiscord.js:795:18)
    at /Users/vasilios/Library/Application Support/discord/0.0.250/modules/discord_desktop_core/core/app/node_modules/betterdiscord/lib/BetterDiscord.js:706:35
    at IncomingMessage.<anonymous> (/Users/vasilios/Library/Application Support/discord/0.0.250/modules/discord_desktop_core/core/app/node_modules/betterdiscord/lib/utils.js:40:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by xMikasa** [comment]
same issue after updating discord.

**Comment by knackrack615** [comment]
Yep, last update broke it
